pipeline{
  agent any

  tools{
    maven 'maven-3.9.7'
    jdk 'JDK-21'
  }
  
  stages{
    stage('Checkout') {
            steps {
                checkout scm
            }
    }
    stage('Build'){
      steps{
        bat 'mvn clean package'
      }
    }
  }
}

  

